#ifndef __guifrmMain__
#define __guifrmMain__

/**
@file
Subclass of frmMain, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include <vector>
#include <wx\dcclient.h>
#include <wx\string.h>
#include <wx/colour.h>
#include <wx/brush.h>
#include <set>
#include <wx\msgdlg.h>
#include <wx/numdlg.h>
#include <stack>
//// end generated include

/** Implementing frmMain */
class guifrmMain : public frmMain
{
	std::pair<int, int> koordtch[50];
	int n = 0;
	int versh = -1;
	bool used[50];
	std::set<int> g[50];
	std::vector<int> path;
	std::vector<std::vector<int>>matr;

	public:
		/** Constructor */
		guifrmMain( wxWindow* parent );
	//// end generated class members
		void create_node(wxMouseEvent& even);
		void create_nodes(wxMouseEvent& even);
		void euler_click(wxCommandEvent& event);
		void clean(wxCommandEvent& event);
		void start_dfs(wxCommandEvent& event);
		void dfs(int v);
		void short_path(wxCommandEvent& event);
		void paint();
		void search(int v);
};

#endif // __guifrmMain__
